# CodeDeploy 수행 파일
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/trading-app/zip/
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: stop.sh # 스프링 부트를 종료합니다.
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh # 새 버전의 스프링 부트를 시작합니다.
      timeout: 60
      runas: ec2-user
