spring:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}
  mail:
    service: ${SPRING_MAIL_SERVICE}
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          timeout: 3000
          starttls:
            enable: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}
      database: ${SPRING_DATA_REDIS_DATABASE}

# url
upbit:
  api:
    uri: ${UPBIT_API_URI}

# schedule property
schedule:
  fixed:
    delay:
      upbit: ${SCHEDULE_FIXED_DELAY_UPBIT}

application:
  name: news-search
  version: 1.0.0
  external-api:
    kakao:
      scheme: https
      host: ${APPLICATION_EXTERNAL_API_KAKAO_HOST}
      path: ${APPLICATION_EXTERNAL_API_KAKAO_PATH}
      authorization: ${APPLICATION_EXTERNAL_API_KAKAO_AUTH}
    naver:
      scheme: https
      host: ${APPLICATION_EXTERNAL_API_NAVER_HOST}
      path: ${APPLICATION_EXTERNAL_API_NAVER_PATH}
      client-id: ${APPLICATION_EXTERNAL_API_NAVER_CLIENT_ID}
      client-secret: ${APPLICATION_EXTERNAL_API_NAVER_CLIENT_SECRET}

jwt:
  secret-key: ${JWT_SECRET_KEY}

app-key: ${APP_KEY}

developer-email: ${DEVELOPER_EMAIL}

email-send: true

# OpenWeather
openweather:
  appid: ${OPENWEATHER_APIID}

# google
google:
  client-id: ${GOOGLE_CLIENT_ID}

host: ${HOST}

myprofile: defaultt
