spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          show-sql: true
      open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
#    mvc:
#      pathmatch:
#        matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# url
upbit:
  api:
    uri: 'https://api.upbit.com/v1'

# schedule property
schedule:
  fixed:
    delay:
      upbit: 86400000

application:
  name: news-search
  version: 1.0.0
  external-api:
    kakao:
      scheme: https
      host: dapi.kakao.com
      path: /v2/search/news
      authorization: KakaoAK 5a60cf339c638fc06dc05cfe14d28804
    naver:
      scheme: https
      host: openapi.naver.com
      path: /v1/search/news.json
      client-id: CrMVAi4gohyXhms5u4tq
      client-secret: Ug04liJU6z